### ISSUE TITLE
`DEX` - display prices

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1845]
#### What would you like to be added:
We would like to revamp DEX page to ensure that we highlight DEX prices per liquidity pair. 
![image](https://user-images.githubusercontent.com/25013382/154000963-51acc357-a8c9-4f3a-b356-1804266ae9f8.png)

https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?node-id=7570%3A103950

--------------------------------------------------------
#### Subtickets
All tasks below are defined as done when e2e tests for it passed:
- [ ] New tab UI (consider to using 3rd party plugin this time) #2182 
- [ ] Move SWAP button to screen header #2183
- [ ] Updated TVL UI design #2184
- [ ] Update DEX card UI, expanded view, FlatList for card listing #2185 (memoize if necessary, use flatlist)
--------------------------------------------------------

- [ ] Don't add the "Search results for"
![image](https://user-images.githubusercontent.com/25013382/153982190-f07030a1-82da-4801-a750-258d5607bdbc.png)

- [ ] Display prices based on DEX
- [ ] Add filters for DFI and DUSD pairs
- [ ] Updated display for TVL
- [ ] Available pool pairs and Your Pool pairs
